### ISSUE TITLE
loqusdb stage on hasta

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/loqusdb#1]
Contact: @henrikstranneheim @moonso 

Problem: loqusdb needs to be able to be tested on stage and we don't have a solution for this right now.

Suggested solution: Add loqus db to the staging enviroment on hasta and create a stage db to be used.

* Ensure there is a new enviroment for loqusdb stage (S_loqusdb)
* Make sure the S_loqusdb is accessible through S_main
* Make update scripts (prod and stage)
* Ensure there is a loqus_db stage db available on clinical-db (mongo DB)

Q: Any work for TTN:
A: Support, open up any ports if needed.
Q: Do we have any info?
A: Development manual
Q: Do we need to make any scripts available?
A: Yes

**Comment by ingkebil** [comment]
Created:
- loqusdb update scripts
- loqusdb stage db

this is finished?

**Comment by emiliaol** [comment]
Yes! We already burnt 2 points before even starting. Well done!
