### ISSUE TITLE
new loqusdb_rd instance for rare disease

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/loqusdb#2]
As a rare disease customer I want the loqusDB to be clean from contaminating and duplicated samples so that I can trust the frequency when analysing my cases and make informed decisions for diagnosis.

Contact: @henrikstranneheim 

**Problem:** The current version of the loqusDB instance contains some probable contaminating samples due to the following problems:
 1. Clinical Genomics performs development and validation runs, which should not be added to LoqusDb
 2. User provide multiple case and sample ids, hence we cannot rely on a mapping to customer sample ids. User provide multiple DNA submissions for the same sample, hence we cannot rely on our LIMS ID to always represent the same sample.

These samples inflate the local frequency count of variants and this might affect the analysis of the cases.

**Suggested solution:**
1. Information of customer associated with the analysis need to be relayed to cg upload and import restricted to cust002-004 -> **DONE**
2. Use MAF variants from MPS to perform check in loqusdb for existence of MAF profile in samples imported in database. LoqusDb will skip load if MAF profile already present. **ONGOING by AR, HS and MM, will be completed by sprint start 3/4 2019**
3. Clean up the current loqusDB instance by creating a new instance called loqusdb_rd. **DONE** 
4. The new instance needs to be populated by looping over the cust002-004 WGS cases (latest bundle) and import to the new loqusdb_rd. Only cases with the sample `Analysis Type` = MIP should be added.
4. Make sure that loqusdb only uploads the MIP analysis type cases in the `cg upload observations`. This code should be able to separate upload to different loqusdb instances based on `Analysis Type`. -> `cg upload observations`. Can't be in production until the new loqusdb version is in production (coordinated release).
4. Create US or Create two additional loqusdb instances: `loqusdb_cancer` and `loqusdb_germline_cancer`. Samples with the `Analysis Type` = MIP + Balsamic and not `Is Tumor` should go to loqusdb_germline_cancer. Samples with `Analysis Type` = MIP + Balsamic and `Is Tumour` = yes + samples with `Analysis Type` = Balsamic should go to loqusdb_cancer. **made new US, so DONE**
5. document in --help

DoD:
New db ready for use and cg upload observation ready to be merged.

How to demo?

**Comment by patrikgrenfeldt** [comment]
Leukemia case: MIP + is_tumor should go to cancer database since we expect the same type dna changes (in a fairly broad sense) in all cancers
