### ISSUE TITLE
Houston, we have a problem!

### ISSUE THREAD

**Issue by J35P312** [Clinical-Genomics/loqusdb#48]
Hello there!
I noticed a bug in the latest version of the SV branch (from line 97 in in the plugins/mongo/structural_variant.py):

        if cluster['sv_type'] != 'BND':
            cluster_len = end_mean - pos_mean
            # We need to adapt the interval size depending on the size of the cluster
            divider = 10
            if cluster_len < 1000:
                # We allow intervals for smaller variants to be relatively larger
                divider = 2
            elif cluster_len < 1000:
                # We allow intervals for smaller variants to be relatively larger
                divider = 5
            interval_size = int(min(round(cluster_len/divider, -2), max_window))
else:

I see that the cluster_len limit for the "if" and "elif" statments are the same (i.e 1000)! Should we keep it like this during our benchmarking? Or should we fix it and redo the benchmarking?
Regards
Jesper

**Comment by moonso** [comment]
Nice spotting!

**Comment by J35P312** [comment]
That's great, nicely done! We should try to make a release for the article as soon as possible!
