### ISSUE TITLE
Index on non-existing key

### ISSUE THREAD

**Issue by adrosenbaum** [Clinical-Genomics/loqusdb#71]
In the variant collection, the key for the position is 'start' not 'pos'

https://github.com/moonso/loqusdb/blob/bff9afe3fd69d02716e1c37ad0e806b75e161e0e/loqusdb/plugins/mongo/variant.py#L29-L35

However, the index is built on a non-existing 'pos' key

https://github.com/moonso/loqusdb/blob/bff9afe3fd69d02716e1c37ad0e806b75e161e0e/loqusdb/__init__.py#L10-L17

This would mean that currently the index is built on a key that does not exist in the database.

**Comment by moonso** [comment]
Great @adrosenbaum , I'll fix that
