### ISSUE TITLE
REST interface

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/loqusdb#76]
A small REST-esque service to query and update db to accompany the nifty CLI. This may be quicker for common use, as the app can stay resident and not have to load each time. Also potentially easier for integration in different apps.

**Comment by moonso** [comment]
I'm finally on it!

**Comment by moonso** [comment]
Fixed in https://github.com/Clinical-Genomics/loqusdbapi 😄 . Please try it out @dnil !

**Comment by moonso** [comment]
This is only a GET api at the moment, should be sufficient for usage with Scout. Will add more complete API when need arises. Please open issues about it in the other repo
