### ISSUE TITLE
RESTapi for containerization

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/loqusdb#79]
I am working with deploying Scout (and related services) as a docker swarm and would like to use loqusdb. However it seems from the documentation that Scout needs to have access to the loqusdb executable which would necessitate that they are located in the same container.

Do you plan to turn loqusdb into a service with an RESTapi?

**Comment by moonso** [comment]
Hi @mhkc  nice to hear that you are working on it! Please check issue #76 
So the rest api exists but the code in scout is not adapted to use it. Perhaps this can be something to discuss in the upcoming developer meeting.

Also @eriksjolund here at clinical genomics has started with an example how to deploy scout in rootless containers (podman) here: https://github.com/eriksjolund/scout/tree/podman_systemd

**Comment by mhkc** [comment]
Cool! Is someone working on adapting scout to use the API?

**Comment by moonso** [comment]
Not that I know of, but perhaps check with @dnil and @northwestwitch.

**Comment by northwestwitch** [comment]
I haven't considered working on that yet. We could add it to the to do list!

**Comment by dnil** [comment]
Yes, I typically think about it for a few seconds every time the CLI calls fail and return an email.. We also have issue #2169 related to loqus integration. Might be a nice small project.

**Comment by mhkc** [comment]
I think it could be good to prioritize this as it would make our overall strive to containerize scout and related softwares easier.

**Comment by northwestwitch** [comment]
This is issue can be closed now as Scout >=4.34 is supporting connections to LoqusDB APIs (via https://github.com/Clinical-Genomics/loqusdbapi)
